Check for openssl, improve error handling

diff --git a/new_test_site b/new_test_site
--- a/new_test_site
+++ b/new_test_site
@@ -86,6 +86,13 @@ if [ "$#" -ne 1 ]; then
 	exit 1
 fi
 
+which openssl > /dev/null 2>&1
+
+if [ "$?" -ne "0" ]; then
+	>&2 echo "Error: openssl not found on path"
+	exit 1
+fi
+
 apache_conf_dir=/etc/httpd/conf.d
 cert_dir=/etc/pki/tls/certs
 key_dir=/etc/pki/tls/private
@@ -224,13 +231,18 @@ if [[ ! "$branch" =~ $old_versions ]]; then
 	install_args+=("--adminemail=admin@example.com")
 fi
 
-php -f $sitedir/moodle/admin/cli/install.php -- "${install_args[@]}" > /dev/null
+installoutput=$(mktemp -t "$(basename $0).XXXXXXXXXX")
+
+php -f $sitedir/moodle/admin/cli/install.php -- "${install_args[@]}" > $installoutput
 
 if [ "$?" -ne "0" ]; then
 	>&2 echo "Error: Install command failed."
+    tail $installoutput
+    rm -f $installoutput
 	exit 1
 fi
 
+rm -f $installoutput
 chown $www_user $sitedir/moodle/config.php
 
 openssl req -x509 -newkey rsa:4096 -keyout $key_file -out $cert_file -days 720 -nodes -subj "/CN=$domain_name" > /dev/null
