new_test_site Support for 2-digit minor version
-t allows a tag (e.g. v3.5.10) but uses the major (e.g. 3) and minor (e.g.
5) parts to construct the branch (e.g. MOODLE_35_STABLE) to know which
options admin/cli/install.php the version supports.  When constructing the
branch the minor version was assumed to be one digit but with the release
of 3.10, these can now be two.  This change adds support for this so that,
e.g. -t v3.10.1, works.

diff --git a/new_test_site b/new_test_site
--- a/new_test_site
+++ b/new_test_site
@@ -48,7 +48,14 @@ while getopts "g:b:t:h?v" opt; do
 		g) upstream_repo=$OPTARG
 			;;
 		t) tag=$OPTARG
-			branch=MOODLE_${tag:1:1}${tag:3:1}_STABLE
+			regex="v([0-9]+)\.([0-9]+)\."
+
+			if [[ $tag =~ $regex ]]; then
+				branch=MOODLE_${BASH_REMATCH[1]}${BASH_REMATCH[2]}_STABLE
+			else
+				>&2 echo "Error: Tag $tag does not match 'vX.Y.Z'."
+				exit 1
+			fi
 			;;
 		h|\?) show_help
 			exit 0
